# Application Configuration
spring.application.name=team20-Tim-Djordjina
server.port=8080

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/ride_on_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_APP_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Sendgrid Email Configuration
#sendgrid.api.key=${SENDGRID_API_KEY}
#sendgrid.from.email=${SENDGRID_FROM_EMAIL}
sendgrid.from.name=${SENDGRID_FROM_NAME}

# JWT (JSON Web Token)
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Application Base URL
#app.base-url=http://localhost:8080
app.base-url=${APP_BASE_URL}
app.reset-password-deeplink=rideon://reset-password

ride.price.standard=200
ride.price.luxury=500
ride.price.van=350

ride.scheduler.interval-ms=30000

# production-like defaults
reminder.lead-minutes=15
reminder.interval-minutes=5
reminder.check-interval-ms=60000

# for a live demo
# reminder.lead-minutes=2
# reminder.interval-minutes=1
# reminder.check-interval-ms=15000
